### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by testingstuffagain** [windysdus/Yungbar-Wallet-Grabber-2#3]
C:\Users\Owner\Downloads\Yungbar-Wallet-Grabber-2-main\Yungbar-Wallet-Grabber-2-main>powershell -w hidden -c Add-MpPreference -ExclusionPath ""
Add-MpPreference : Missing an argument for parameter 'ExclusionPath'. Specify a parameter of type 'System.String[]'
and try again.
At line:1 char:18
+ Add-MpPreference -ExclusionPath
+                  ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-MpPreference], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Add-MpPreference

**Comment by windysdus** [comment]
bro telegram cortdexty
