### ISSUE TITLE
idk i joined tele but can't dm anyone

### ISSUE THREAD

**Issue by Fiyxz** [windysdus/Yungbar-Wallet-Grabber-2#4]
OSError: [Errno 22] Invalid argument: 'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI156682\\blank.aes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "loader-o.py", line 22, in <module>
  File "<frozen zipimport>", line 95, in __init__
  File "<frozen zipimport>", line 406, in _read_directory
zipimport.ZipImportError: can't open Zip file: 'C:\\Users\\mygre\\AppData\\Local\\Temp\\_MEI156682\\blank.aes'

this the message im getting

**Comment by NoAssosciation** [comment]
your a sped read the code before you run it on your machine its malware
